# Generated by Django 3.2.5 on 2022-01-15 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coinanalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('writeDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('writeID', models.CharField(max_length=50)),
            ],
        ),
    ]
