# Generated by Django 3.2.5 on 2022-01-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinanalysis', '0004_auto_20220117_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoiner',
            name='close',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitcoiner',
            name='high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitcoiner',
            name='low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitcoiner',
            name='open',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitcoiner',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitcoiner',
            name='volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bitcoiner',
            name='won',
            field=models.FloatField(default=0.0),
        ),
    ]
