# Generated by Django 3.2.5 on 2022-01-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinanalysis', '0005_auto_20220117_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoiner',
            name='value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bitcoiner',
            name='volume',
            field=models.FloatField(default=0.0),
        ),
    ]
