# Generated by Django 3.2.5 on 2022-01-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinanalysis', '0006_auto_20220117_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoiner',
            name='date',
            field=models.DateField(),
        ),
    ]
